image: ubuntu/focal
packages:
  - curl
  - build-essential
  - git
  - rsync
  # learn uxn
  - libsdl2-dev
  # cypress
  - libgtk2.0-0
  - libgtk-3-0
  - libgbm-dev
  - libnotify-dev
  - libgconf-2-4
  - libnss3
  - libxss1
  - libasound2
  - libxtst6
  - xauth
  - xvfb
sources:
  - https://git.sr.ht/~metasyn/learn-uxn
secrets:
  - b336eab6-3f41-4b59-99ba-9132cadc232f
tasks:
  - node: |
      curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh
      sudo bash nodesource_setup.sh
      sudo apt-get install -qq -y nodejs
  - build: |
      cd learn-uxn
      make build
  - test: |
      cd learn-uxn
      make serve test
  - deploy: |
      cd learn-uxn
      git remote add github git@github.com:metasyn/learn-uxn
      sh-keyscan github.com >> ~/.ssh/known_hosts
      git push github master
