image: ubuntu/focal
packages:
  - curl
  - build-essential
  - git
  - rsync
  # learn uxn
  - libsdl2-dev
  # cypress
  - libgtk2.0-0
  - libgtk-3-0
  - libgbm-dev
  - libnotify-dev
  - libgconf-2-4
  - libnss3
  - libxss1
  - libasound2
  - libxtst6
  - xauth
  - xvfb
sources:
  - https://git.sr.ht/~metasyn/learn-uxn
secrets:
  - 46f739e5-4538-45dd-a79f-bf173b7a2ed9
tasks:
  - node: |
      curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh
      sudo bash nodesource_setup.sh
      sudo apt-get install -qq -y nodejs
  - build: |
      cd learn-uxn
      make build
  - test: |
      cd learn-uxn
      make serve test
  - deploy: |
      cd learn-uxn
      git remote add github git@github.com:metasyn/learn-uxn.git
      mkdir -p ~/.ssh
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      git config user.name "builds.sr.ht"
      git config user.email "xander@metasyn.pw"
      git checkout master
      git pull github master
      git add docs && git commit -m ":robot: automatic build from builds.sr.ht"
      git push github master
